services:
  Fourxxi\RestRequestError\Factory\View\ErrorViewFactory: ~
  Fourxxi\RestRequestError\Serializer\InvalidRequestExceptionNormalizer:
    arguments:
      - '@Fourxxi\RestRequestError\Factory\View\ErrorViewFactory'